// @ts-check
// Generated by Deepfield — {{SNAPSHOT_VERSION}} ({{SNAPSHOT_DATE}})
// Do not edit directly; re-run `deepfield docs build` to regenerate.

import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: '{{PROJECT_NAME}} Knowledge Base',
  tagline: 'AI-generated knowledge base — {{SNAPSHOT_VERSION}}',
  favicon: 'img/favicon.ico',

  url: 'https://your-site.example.com',
  baseUrl: '/',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  customFields: {
    // Giscus configuration for section feedback
    // Set giscusRepo to enable per-section comments.
    giscusRepo: '{{GISCUS_REPO}}',
    giscusRepoId: '{{GISCUS_REPO_ID}}',
    giscusCategoryId: '{{GISCUS_CATEGORY_ID}}',
    feedbackEnabled: '{{FEEDBACK_ENABLED}}',
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.js',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: '{{PROJECT_NAME}}',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'knowledgeSidebar',
          position: 'left',
          label: 'Knowledge Base',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `Generated by <a href="https://github.com/TomazWang/deepfield">Deepfield</a> — ${new Date().getFullYear()}`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
