import { readdir, readFile, writeFile, ensureDir } from 'fs-extra';
import fsExtra from 'fs-extra';
const { readdir: fseReaddir, readFile: fseReadFile, writeFile: fseWriteFile, ensureDir: fseEnsureDir, pathExists } = fsExtra;
import { join, relative, dirname, basename, extname } from 'path';
import matter from 'gray-matter';
import type { TransformResult } from './types.js';

const TIER_DIRS = ['context', 'tech-design', 'implementation', 'cross-cutting'];
const LEGACY_DIR = 'domains';

/**
 * Derive a human-readable title from a filename.
 * e.g. "auth-service" → "Auth Service", "tech-design" → "Tech Design"
 */
function filenameToTitle(name: string): string {
  return name
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Extract title from the first # heading in markdown content.
 * Falls back to filename-derived title.
 */
function extractTitle(content: string, fallback: string): string {
  const match = content.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : filenameToTitle(fallback);
}

/**
 * Shorten a sidebar label: strip leading "Domain Name — " prefix if present.
 */
function shortenLabel(title: string): string {
  // "Auth Service — Technical Design" → "Technical Design"
  const dashMatch = title.match(/^.+\s[—–-]\s+(.+)$/);
  return dashMatch ? dashMatch[1] : title;
}

/**
 * Detect the workspace structure type from the snapshot directory.
 */
async function detectStructure(
  snapshotPath: string
): Promise<'3-tier' | 'domains' | 'flat'> {
  const tierCount = (
    await Promise.all(TIER_DIRS.map((d) => pathExists(join(snapshotPath, d))))
  ).filter(Boolean).length;

  if (tierCount >= 2) return '3-tier';
  if (await pathExists(join(snapshotPath, LEGACY_DIR))) return 'domains';
  return 'flat';
}

/**
 * Recursively collect all .md files under a directory.
 * Returns paths relative to the base directory.
 */
async function collectMarkdownFiles(dir: string, base: string = dir): Promise<string[]> {
  const entries = await fseReaddir(dir, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await collectMarkdownFiles(fullPath, base)));
    } else if (entry.isFile() && extname(entry.name) === '.md') {
      results.push(relative(base, fullPath));
    }
  }

  return results.sort();
}

/**
 * Process a single markdown file: inject Docusaurus frontmatter if missing,
 * write to docs output path.
 */
async function processMarkdownFile(
  srcPath: string,
  destPath: string,
  relativePath: string,
  position: number
): Promise<void> {
  const raw = await fseReadFile(srcPath, 'utf-8');
  const parsed = matter(raw);

  // Don't add frontmatter if it already exists and has a title
  if (parsed.data.title) {
    await fseEnsureDir(dirname(destPath));
    await fseWriteFile(destPath, raw, 'utf-8');
    return;
  }

  const fileBase = basename(relativePath, '.md');
  const title = extractTitle(parsed.content, fileBase);
  const sidebarLabel = shortenLabel(title);

  const frontmatter = {
    title,
    sidebar_label: sidebarLabel,
    sidebar_position: position,
  };

  const output = matter.stringify(parsed.content, frontmatter);
  await fseEnsureDir(dirname(destPath));
  await fseWriteFile(destPath, output, 'utf-8');
}

/**
 * Generate sidebars.js content based on detected structure.
 */
function generateSidebars(structure: '3-tier' | 'domains' | 'flat'): string {
  if (structure === '3-tier') {
    return `// @ts-check
// Auto-generated by Deepfield — do not edit manually.
// Re-run \`deepfield docs build\` to regenerate.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  knowledgeSidebar: [
    { type: 'doc', id: 'intro', label: 'Overview' },
    {
      type: 'category',
      label: 'Context',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'context' }],
    },
    {
      type: 'category',
      label: 'Technical Design',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'tech-design' }],
    },
    {
      type: 'category',
      label: 'Implementation',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'implementation' }],
    },
    {
      type: 'category',
      label: 'Cross-Cutting',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'cross-cutting' }],
    },
  ],
};

export default sidebars;
`;
  }

  if (structure === 'domains') {
    return `// @ts-check
// Auto-generated by Deepfield — do not edit manually.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  knowledgeSidebar: [
    { type: 'doc', id: 'intro', label: 'Overview' },
    {
      type: 'category',
      label: 'Domains',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'domains' }],
    },
  ],
};

export default sidebars;
`;
  }

  // flat — full autogeneration
  return `// @ts-check
// Auto-generated by Deepfield — do not edit manually.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  knowledgeSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
`;
}

/**
 * Mirror all markdown from snapshotPath into docsDestPath with Docusaurus
 * frontmatter injected. Returns transform metadata.
 */
export async function transformSnapshot(
  snapshotPath: string,
  docsDestPath: string
): Promise<TransformResult> {
  const structure = await detectStructure(snapshotPath);
  const allFiles = await collectMarkdownFiles(snapshotPath);

  // Track per-directory position counters
  const positionCounters: Record<string, number> = {};

  let docsCount = 0;

  for (const relPath of allFiles) {
    const srcFull = join(snapshotPath, relPath);
    const dirKey = dirname(relPath);
    positionCounters[dirKey] = (positionCounters[dirKey] ?? 0) + 1;
    const position = positionCounters[dirKey];

    // SNAPSHOT.md → intro.md (landing page)
    if (basename(relPath) === 'SNAPSHOT.md') {
      const raw = await fseReadFile(srcFull, 'utf-8');
      const parsed = matter(raw);
      const introFrontmatter = {
        title: 'Knowledge Base Overview',
        sidebar_label: 'Overview',
        sidebar_position: 1,
        slug: '/',
      };
      const output = matter.stringify(parsed.content, introFrontmatter);
      const destFull = join(docsDestPath, 'intro.md');
      await fseEnsureDir(dirname(destFull));
      await fseWriteFile(destFull, output, 'utf-8');
      docsCount++;
      continue;
    }

    const destFull = join(docsDestPath, relPath);
    await processMarkdownFile(srcFull, destFull, relPath, position);
    docsCount++;
  }

  const sidebarCategories =
    structure === '3-tier'
      ? TIER_DIRS
      : structure === 'domains'
        ? [LEGACY_DIR]
        : ['.'];

  return { docsCount, sidebarCategories, structureType: structure };
}

export { generateSidebars, detectStructure };
