'use strict';

const fs = require('fs');
const path = require('path');

module.exports = {
  from: '1.0.0',
  to: '2.0.0',
  description: 'Add domain-based organization (domain-index, drafts/domains/, cross-cutting migration)',

  /**
   * Return true if this migration has NOT yet been applied.
   */
  async check(projectPath) {
    const domainIndex = path.join(projectPath, 'deepfield', 'wip', 'domain-index.md');
    return !fs.existsSync(domainIndex);
  },

  async migrate(projectPath) {
    const deepfieldDir = path.join(projectPath, 'deepfield');
    const changes = [];

    // 1. Create deepfield/wip/domain-index.md
    const domainIndexPath = path.join(deepfieldDir, 'wip', 'domain-index.md');
    if (!fs.existsSync(domainIndexPath)) {
      fs.mkdirSync(path.dirname(domainIndexPath), { recursive: true });
      fs.writeFileSync(domainIndexPath, [
        '# Domain Index\n',
        '<!-- Auto-generated by deepfield. Lists discovered domains and their status. -->\n',
        '## Domains\n',
        '<!-- Add domains here as they are discovered -->\n',
      ].join('\n'));
      changes.push('Created wip/domain-index.md');
    }

    // 2. Ensure deepfield/drafts/domains/ exists
    const domainsDir = path.join(deepfieldDir, 'drafts', 'domains');
    if (!fs.existsSync(domainsDir)) {
      fs.mkdirSync(domainsDir, { recursive: true });
      changes.push('Created drafts/domains/ directory');
    }

    // 3. Move any .md files directly in deepfield/drafts/ (not in subdirs) to cross-cutting/
    const draftsDir = path.join(deepfieldDir, 'drafts');
    const crossCuttingDir = path.join(draftsDir, 'cross-cutting');
    fs.mkdirSync(crossCuttingDir, { recursive: true });

    if (fs.existsSync(draftsDir)) {
      const entries = fs.readdirSync(draftsDir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
        // Skip _changelog.md — it belongs at drafts root
        if (entry.name === '_changelog.md') continue;
        const src = path.join(draftsDir, entry.name);
        const dest = path.join(crossCuttingDir, entry.name);
        if (!fs.existsSync(dest)) {
          fs.renameSync(src, dest);
          changes.push(`Moved drafts/${entry.name} -> drafts/cross-cutting/${entry.name}`);
        }
      }
    }

    return { success: true, changes, filesCreated: changes.length, filesUpdated: 0 };
  },

  async rollback(projectPath) {
    const deepfieldDir = path.join(projectPath, 'deepfield');

    // Remove domain-index.md
    const domainIndexPath = path.join(deepfieldDir, 'wip', 'domain-index.md');
    if (fs.existsSync(domainIndexPath)) fs.unlinkSync(domainIndexPath);

    // Remove drafts/domains/ (only if empty)
    const domainsDir = path.join(deepfieldDir, 'drafts', 'domains');
    if (fs.existsSync(domainsDir)) {
      const entries = fs.readdirSync(domainsDir);
      if (entries.length === 0) fs.rmdirSync(domainsDir);
    }

    return { success: true };
  },
};
